import time

import pytest
from selenium import webdriver
from selenium.common import NoSuchElementException
from selenium.webdriver.common.by import By

from PageObject.AddEmployeePage import AddEmployee
from PageObject.LoginPage import loginpage
from Utilities.ReadProperties import Readconfig
from Utilities.Logger import LogGenerator


class Test_AddEmp:
    Url = Readconfig.geturl()
    username = Readconfig.getusername()
    password = Readconfig.getpassword()
    log = LogGenerator.loggen()

    @pytest.mark.sanity
    def test_addemp_003(self,setup):
        self.driver = setup
        self.log.info("test_addemp_003 Started")
        self.log.info("Opening Browser")
        self.driver.get(self.Url)
        self.log.info("Going to this Url---->"+self.Url)
        self.ae = AddEmployee(self.driver)
        # driver = webdriver.Chrome()
        # driver.implicitly_wait(5)
        # driver.get("https://opensource-demo.orangehrmlive.com/")
        self.lp = loginpage(self.driver)
        self.log.info("login page open")
        self.lp.Enter_UserName(self.username)
        self.log.info("Entering Username-->"+self.username)
        self.lp.Enter_Passwaord(self.password)
        self.log.info("Entering password-->"+self.password)
        self.lp.Click_login()
        self.log.info("Click on login Button")



        # self.driver.find_element(By.XPATH, "//input[@placeholder='Username']").send_keys("Admin")
        # self.driver.find_element(By.XPATH, "//input[@placeholder='Password']").send_keys("admin123")
        # self.driver.find_element(By.XPATH, "//button[normalize-space()='Login']").click()


        self.ae.Click_PIM_Menu_Button()
        self.log.info("Click on PIM_Menu Button")

        self.ae.Click_Add_Button()
        self.log.info("Click on Add_Button")

        self.ae.Enter_FirstName("Komal")
        self.log.info("Entering Firstname-->")

        self.ae.Enter_MiddleName("Vish")
        self.log.info("Entering Middlename-->")

        self.ae.Enter_LastName("M")
        self.log.info("Entering Lastname-->")

        self.ae.Click_save_Button()
        self.log.info("Click on save_Button")



        # self.driver.find_element(By.XPATH,"//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name'][normalize-space()='PIM']").click()
        # self.driver.find_element(By.XPATH,"//i[@class='oxd-icon bi-plus oxd-button-icon']").click()
        # self.driver.find_element(By.XPATH,"//input[@placeholder='First Name']").send_keys("Komal")
        # self.driver.find_element(By.XPATH,"//input[@placeholder='Middle Name']").send_keys("V")
        # self.driver.find_element(By.XPATH,"//input[@placeholder='Last Name']").send_keys("M")
        # #driver.find_element(By.XPATH,"//input[@class='oxd-input oxd-input--focus'][normalize-space()='Employee Id']").send_keys("274") ###autogenerated emp id
        # #time.sleep(3)
        # self.driver.find_element(By.XPATH,"//button[@type='submit']").click()
        #
        if  self.ae.AddEmployee_Status()==True:
            self.driver.save_screenshot("D:\\Automation selinium\\Automation testing python selinium tushar sir\\OrangeHRM Project\\ScreenShoots\\test_addemp_003_Passed.PNG")
            self.log.info("test_addemp_003 Testcase is Passed.")
            self.lp.Click_menu()
            self.log.info("Clicking on Menu_Button")

            self.lp.Click_logout()
            self.log.info("Clicking on Logout Button")

            assert True
        else:
            self.driver.save_screenshot("D:\\Automation selinium\\Automation testing python selinium tushar sir\\OrangeHRM Project\\ScreenShoots\\test_addemp_003_Failed.PNG")
            self.log.info("test_addemp_003 Testcase is Failed.")

            assert False

        self.driver.close()
        self.log.info("<-------test_addemp_003 Testcase is Completed Successfully------>")
        #
        # try:
        #     self.driver.find_element(By.XPATH,"//h6[normalize-space()='Personal Details']")
        #     print("test_addemp_002 TestCase is pass")
        #     self.driver.find_element(By.XPATH, "//p[@class='oxd-userdropdown-name']").click()
        #     self.driver.find_element(By.XPATH, "//a[normalize-space()='Logout']").click()
        #     assert True
        #
        # except NoSuchElementException:
        #     print("test_addemp_002 TestCase is Fail")
        #     assert False

        




